engines:
    coverage:
        enabled: true
        exclude_paths:
          - tests
          - tasks
    metrics:
        enabled: true
    duplication:
        enabled: true
    prospector:
        enabled: true
    pylint:
        enabled: true
        python_version: 3.5
    bandit:
        enabled: true
    remarklint:
        enebled: true
exclude_paths: 
  - migrations
